
schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
      - master
    always: true

trigger:
- master

jobs:
    - job: Linux
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
          Python38:
            python.version: '3.8'
      steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to path
      - script: conda create -y -n test -c numerics88 -c conda-forge python=$(python.version) n88tools
        displayName: Setup conda for testing
      - script: |
          source activate test
          pip install -e .
        displayName: Install bonelab
      - script: |
          source activate test
          nosetests tests
        displayName: Test
    